# Generated by Django 4.2 on 2023-04-24 18:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('job', '0002_alter_studentuser_mobileno'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecruiterReg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobileNo', models.CharField(max_length=10)),
                ('profileImage', models.FileField(upload_to='')),
                ('gender', models.CharField(max_length=10)),
                ('company', models.CharField(max_length=90)),
                ('status', models.CharField(max_length=20)),
                ('type', models.CharField(max_length=15)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
