# Generated by Django 4.2 on 2023-05-19 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0008_alter_job_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='joburl',
            field=models.URLField(default='NULL', max_length=1000),
        ),
        migrations.AlterField(
            model_name='job',
            name='image',
            field=models.FileField(default=0, upload_to=''),
            preserve_default=False,
        ),
    ]
